### ISSUE TITLE
Problemas na criação de dos menus de reclassificação

### ISSUE THREAD

**Issue by eduardojsilvajr** [1cgeo/Ferramentas_Producao#3]
Criei um banco na modelagem edgv 2.13 pro, usando o DSGTools 4(atualizado em 08 nov).

Depois de abrir o Ferramentas de podução no modo LOCAL, ao selecionar o banco na modelagem edgv 2.13 pro recebo uma mensagem de erro porém ao selecionar os bancos que estavam na modelagem 2.13 não há problema.

ao selecionar o banco na modelagem edgv pro, ele não habilita as unidades de trabalho relacionadas
![image](https://user-images.githubusercontent.com/21279385/69184287-f78c1800-0aea-11ea-881f-84dd9ef18381.png)

log de erro:
![image](https://user-images.githubusercontent.com/21279385/69184249-dfb49400-0aea-11ea-9eac-6a18054e71ed.png)

ao selecionar um banco com modelagem 2.13, não há problema:
![image](https://user-images.githubusercontent.com/21279385/69184416-34f0a580-0aeb-11ea-9c4a-5439962060ef.png)

DSG tools 4
Ferramenta de produção: 3.4.14.1
SO: ubuntu 18.04

**Comment by dinizime** [comment]
Bug resolvido. Nova versão 3.4.14.2

O bug era devido a esse banco não conter o atributo "mi" na tabela de moldura. Ele utiliza esse atributo para criar as opções de filtro espacial.

O comportamento agora será: se a moldura não possuir o atributo "mi" não terá opção de filtro espacial pelo modo local. Caso necessite utilizar o filtro espacial criar o atributo "mi" na tabela de moldura.
